name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags : |
            ${{ secrets.DOCKER_USERNAME }}/auto-ops-backend:latest
            ${{ secrets.DOCKER_PASSWORD }}/auto-ops-backend:${{ github.sha }}

      - name: Build frontend image and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags : |
            ${{ secrets.DOCKER_USERNAME }}/auto-ops-frontend:latest
            ${{ secrets.DOCKER_PASSWORD }}/auto-ops-frontend:${{ github.sha }}    


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' 

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install 

      - name: Build project
        working-directory: ./frontend
        run: npm run build 